### ISSUE TITLE
Add TDD to the site

### ISSUE THREAD

**Issue by tnh** [cevoaustralia/cevoaustralia.github.io#115]
Add htmlproofer or similar into the build to make sure links are valid.
https://jekyllrb.com/docs/continuous-integration/circleci/

**Comment by stan1y** [comment]
`bundle exec htmlproofer`
this should be a part of our `make test` in codeship or travis.

**Comment by nonspecialist** [comment]
This is addressed by PR #314

**Comment by nonspecialist** [comment]
PR #312 and #314 have been merged which fix this
