### ISSUE TITLE
Issues with thumbnail images for case studies on new site

### ISSUE THREAD

**Issue by mngau** [cevoaustralia/cevoaustralia.github.io#128]
The images are hiding the text descriptions
[ ] Equiem technology review
[ ] Aconex terraform-ed infrastructure

Some examples from Chrome;
![image](https://user-images.githubusercontent.com/6792829/30695881-2238aa50-9f1d-11e7-854e-288a155a9fa1.png)
![image](https://user-images.githubusercontent.com/6792829/30696040-97a83530-9f1d-11e7-9549-60f60aa30ce3.png)

Below is not critical but if it's related to the issues above then maybe it will be fixed when the above are.
[ ] Monash University image is also seems to be shifting a bit in a smaller responsive mode
![image](https://user-images.githubusercontent.com/6792829/30696118-da485c08-9f1d-11e7-9f30-75bdc80a2791.png)
![image](https://user-images.githubusercontent.com/6792829/30696145-fab47eb8-9f1d-11e7-8f46-298026491fe5.png)

**Comment by stan1y** [comment]
<img width="880" alt="screen shot 2017-09-24 at 10 21 46 am" src="https://user-images.githubusercontent.com/117665/30778185-6e40d0ac-a112-11e7-9eed-650f91557b4e.png">
<img width="398" alt="screen shot 2017-09-24 at 10 22 21 am" src="https://user-images.githubusercontent.com/117665/30778186-6e433694-a112-11e7-8ca8-ad968ad5815f.png">
<img width="475" alt="screen shot 2017-09-24 at 10 22 35 am" src="https://user-images.githubusercontent.com/117665/30778187-6e46f716-a112-11e7-967c-975226a96c26.png">


Current state of `new.cevo.com.au`

**Comment by stan1y** [comment]
`max-width/height: 300px;`
