### ISSUE TITLE
Testimonials are too hard to read

### ISSUE THREAD

**Issue by nonspecialist** [cevoaustralia/cevoaustralia.github.io#132]
The white text with drop shadows is very hard to read against the building background of lit windows.

One way to address this would be with a CSS black underlay with less than 100% opacity (eg `background-color: rgba(0, 0, 0, 0.5)`) but that doesn't look great because it's just the `div` which gets the colouring.

Another way might be to have the background image have a dark gradient applied so that the text is above a darker piece.

**Comment by stan1y** [comment]
addressed in df70a98. Please reopen if still not good for your eyes.
