### ISSUE TITLE
Make asset inclusion protocol relative or https.

### ISSUE THREAD

**Issue by CaseyLeask** [cevoaustralia/cevoaustralia.github.io#151]
https://www.paulirish.com/2010/the-protocol-relative-url/

![screen shot 2017-10-05 at 1 46 45 pm](https://user-images.githubusercontent.com/430277/31208922-a54e1bd0-a9d3-11e7-96cf-dbd68e855eea.png)
![screen shot 2017-10-05 at 1 46 50 pm](https://user-images.githubusercontent.com/430277/31208923-a550c2c2-a9d3-11e7-993f-9b22cd859f6e.png)
![screen shot 2017-10-05 at 1 46 59 pm](https://user-images.githubusercontent.com/430277/31208921-a54c960c-a9d3-11e7-8f53-8adb67d1c348.png)

**Comment by tpartington** [comment]
the base-url has been set to https and i've confirmed this is no longer an issue.
