### ISSUE TITLE
Alignment issue with case study page

### ISSUE THREAD

**Issue by mngau** [cevoaustralia/cevoaustralia.github.io#239]
I noticed something weird with the introduction of the Factor5 case study.
The alignment is funny there’s a large gap.

Also I think the MYOB case study might have a headline that’s maybe pushing the alignment out?

![image](https://user-images.githubusercontent.com/6792829/35312796-65ef1512-0111-11e8-9197-eae4333343e0.png)

**Comment by nonspecialist** [comment]
We appear not to have this problem any more
