### ISSUE TITLE
Blog issues

### ISSUE THREAD

**Issue by mngau** [cevoaustralia/cevoaustralia.github.io#240]
@stevemac007 noticed a couple of issues on the blog:
- Broken avatars for departed team members
- Embedded image on census post is missing
- Embedded images on mapping system posts are missing

**Comment by tpartington** [comment]
Embedded images should now be fixed. Will leave the issue open as we still need to fix the missing avatars.

**Comment by nonspecialist** [comment]
The missing avatars is covered by #312
