### ISSUE TITLE
Fix 'last update' to the website terms of use & privacy policy

### ISSUE THREAD

**Issue by mngau** [cevoaustralia/cevoaustralia.github.io#248]
Include a `LAST UPDATE: 5 FEBRUARY 2018` to the `terms-of-use` page (consistent with our `privacy-policy` page.

It currently looks like this:
<img width="429" alt="screen shot 2018-02-05 at 14 37 23" src="https://user-images.githubusercontent.com/6792829/35787427-2b69960e-0a82-11e8-9694-0c4a6c3a2aca.png">

If possible maybe place this at the top of the page below one of the headings? or at the very bottom with a gap after the content?

**Comment by stan1y** [comment]
Originals are in the GDrive and only one had "last update".

**Comment by mngau** [comment]
Just checked the site, all looks good. We now have 'last updated' consistently across 'terms of use', 'privacy policy' & 'environmental policy'.

**Comment by AdamNowotny** [comment]
Fixed with PR 283
