### ISSUE TITLE
Old Website is still indexed in google and available

### ISSUE THREAD

**Issue by tpartington** [cevoaustralia/cevoaustralia.github.io#280]
Using the contact form as an example:
![google_results](https://user-images.githubusercontent.com/6980747/36575889-7dea54c2-18a1-11e8-8d7f-4d28489a3134.png)

which loads:
![old_form](https://user-images.githubusercontent.com/6980747/36575895-8449bc04-18a1-11e8-84b2-e7fe92c110ff.png)

we should archive and clear the old contents from the bucket.

**Comment by nonspecialist** [comment]
This behaviour appears to be fixed -- searching for the same string doesn't return the old link for me, and even visiting the old link gives me the new contact form. Closing as fixed.
