### ISSUE TITLE
Update 2018 environmental policy to website

### ISSUE THREAD

**Issue by mngau** [cevoaustralia/cevoaustralia.github.io#288]
Link to google document;
https://docs.google.com/document/d/1VpvHwWIxmLBY4jUJECqVcLO0VEcKz_0c83tDbKMwcIo

Link to word document; https://drive.google.com/open?id=1turZNK1WY7xNABZ5L3Ea-lLTh5KjB0z_

Link to pdf document; https://drive.google.com/open?id=1moutfXO-_x1IAXbn3edEJ9fcYpnk7Gv9

@SianHughes may have a suggestion for where this should be linked/made visible on our site.

**Comment by AdamNowotny** [comment]
Fixed with PR 283
