### ISSUE TITLE
Portraits of old team members who have authored content on the site

### ISSUE THREAD

**Issue by mngau** [cevoaustralia/cevoaustralia.github.io#312]
Some of our blogs were written by ex-cevo colleagues when we remove their profiles (including their portrait photos) it comes up as a broken link on the site.
Proposal
1) Replace the linked with a default photo or
2) Create a new static folder where we keep portrait photos of authors for our blogs who aren't currently in the team

**Comment by nonspecialist** [comment]
Perhaps one option is to just replace the missing person's face with a symlink to a "default" person image. Given I've just broken `develop` by adding htmlproofer which is now complaining about those broken photo links ... I reckon that's the quickest "good enough for now" fix

**Comment by nonspecialist** [comment]
I added a `DEFAULT_PERSON.jpg` and symlinked those missing team images to that ... You can see an example at http://beta.cevo.com.au/post/page/4/
