### ISSUE TITLE
Profile blurbs are too long on some mobiles

### ISSUE THREAD

**Issue by nonspecialist** [cevoaustralia/cevoaustralia.github.io#59]
Most of the people profile blurbs are too long on mobile (iOS 10, iPhone SE) and flow under the photo of the next person in line. This is only the case in portrait orientation -- in landscape, it looks fine.

**Comment by mngau** [comment]
This is specifically an issue for the smaller resolution devices in portrait orientation.

**Comment by mngau** [comment]
Closing as this is resolved in the new site
